### ISSUE TITLE
Return files where a variant was found as list instead of as map

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-ws#1]
The list of files where a variant was found is now returned as a map whose key is a combination of study and file ID. This key is not really useful, and these files should be returned as a list.
Some ideas can be found here: http://stackoverflow.com/questions/11106053/how-to-serialize-a-map-as-list-using-jackson It would be nice to overlap Jackson annotations as least as possible with the rest of the code.

**Comment by AdrianBZG** [comment]
@cyenyxe Hi, I'm trying to understand this issue, can you please tell me where is this mentioned map returned? Is it in StudyWSServer? Thanks!

**Comment by cyenyxe** [comment]
If you run [this query](http://wwwdev.ebi.ac.uk/eva/webservices/rest/v1/segments/1:3000000-3100000/variants?species=athaliana_tair10&page=1&skip=0&limit=2), you will observe that the `sourceEntries` subdocument is a map of "studyId_fileId" to object. Initially we wanted to get rid of the key and just list the objects, but given where the API is at the moment the change is probably not worth it anymore. I will discuss it with the rest of the team but closing it may be the best choice.

**Comment by tcezard** [comment]
This is fixed: Closing
