### ISSUE TITLE
Improve error codes returned in variant search endpoints

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-ws#78]
Variant search endpoints require 2 annotation version parameters: `annot-vep-version` and `annot-vep-cache-version`. The code currently returned when one of them is not is 500, which represents a server error instead of a user input error. This can be tested by accessing the following endpoints removing one of them: 

https://www.ebi.ac.uk/eva/webservices/rest/v1/segments/5:63323000-63325000/variants?exclude=sourceEntries&species=sscrofa_111&annot-vep-version=89&annot-vep-cache-version=89&page=1&skip=0&limit=10

https://www.ebi.ac.uk/eva/webservices/rest/v1/variants/rs81294174/info?species=sscrofa_111&annot-vep-version=89&annot-vep-cache-version=90

http://wwwdev.ebi.ac.uk/eva/webservices/rest/v1/genes/CD163/variants?species=sscrofa_111&annot-vep-version=89&annot-vep-cache-version=91&page=1&skip=0&limit=10

It would be more appropriate to return a HTTP error code 400, because this is a user input problem.

**Comment by AdrianBZG** [comment]
Hi, I want to work on this issue but it's not clear to me what you mean... Do you mean to check in the AnnotationMetadataWSServer, the list of AnnotationMetadata(s) [2], and check if the vepVersion and cacheVersion of all them are NOT null, if one is NULL, then return error 400, right?

For the version is not found, you mean to check that, if the cacheVersion and vepVersion are not null, they need to have a meaningful value? If so, what is the set of correct values for this fields?

Sorry for the questions, I'm new to EVA repositories.

[1] [https://github.com/EBIvariation/eva-ws/blob/develop/eva-server/src/main/java/uk/ac/ebi/eva/server/ws/AnnotationMetadataWSServer.java](https://github.com/EBIvariation/eva-ws/blob/develop/eva-server/src/main/java/uk/ac/ebi/eva/server/ws/AnnotationMetadataWSServer.java)
[2] [https://github.com/EBIvariation/variation-commons/blob/develop/variation-commons-core/src/main/java/uk/ac/ebi/eva/commons/core/models/AnnotationMetadata.java](https://github.com/EBIvariation/variation-commons/blob/develop/variation-commons-core/src/main/java/uk/ac/ebi/eva/commons/core/models/AnnotationMetadata.java)

**Comment by cyenyxe** [comment]
Looking at this ticket in retrospective, its description wasn't correct. I have updated it with some links to the actual endpoints and a better explanation. The endpoints code can be found in `RegionWSServer`, `VariantWSServer` and `GeneWSServer`, respectively.

**Comment by cyenyxe** [comment]
Closed via #84
