### ISSUE TITLE
New REST endpoint that reports number of variants in a database

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-ws#79]
Implement a new REST endpoint that returns the total number of variants in a database.

**Comment by JosemyDuarte** [comment]
I could try to help with this... What do you mean about variants?

**Comment by cyenyxe** [comment]
Our database stores genomic variants, each being stored as a record. So the endpoint would just count how many records are in the MongoDB collection that contains those variants.

**Comment by AdrianBZG** [comment]
Hi, I have added a REST endpoint to count the number of variants over all studies, it gets as optional parameters "species" and "types", after that gets all the studies according to that specified parameters or just all of them in other case, loops over them adding up the getNumVariants(). Pull request on #83.

I hope it's ok and it's useful, just tell me if it's not, thanks!

**Comment by cyenyxe** [comment]
Closed via #83
