### ISSUE TITLE
Report studies added to MongoDB database after a certain date

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-ws#85]
When a study is loaded into the database, a collection with the information about the files in said study is populated. This collection contains the date when the study was loaded, among other fields.

Some of our users run services that consume subsets of the EVA data periodically, and they have requested an endpoint to discover if any studies have been loaded since a given date. Otherwise they would just not trigger their import processes.

This endpoint could be based on the existing one that already lists all the studies in a species, but with an additional filter.

**Comment by tcezard** [comment]
Tracked in EVA-1736: closing
