### ISSUE TITLE
EVA-943 Annotation exclusion does not work

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-ws#87]
Endpoints like `segments/<region>/variants` support an "exclude" parameter, but excluding the annotation is not working at the moment. The following map shows which values can be used to exclude which fields:

```java
Map<String, String> map = new HashMap<>();
map.put("sourceEntries", "files");
map.put("sourceEntries.statistics", "st");
map.put("annotation", "annot");
map.put("sourceEntries.attributes", "files.attrs");
return map;
```

but this is only used in the `VariantRepository`, not in the `VariantWithSamplesAndAnnotationsService`, and the latter merges the annotation from the annotations collection ignoring the "exclude" parameter.

In addition to fixing the bug, the code documentation should be improved to clarify how the "exclude" works.

**Comment by AdrianBZG** [comment]
Hi @cyenyxe, can you give me a ws query to check this please? Thanks

**Comment by AdrianBZG** [comment]
@cyenyxe The VariantRepository already excludes (https://github.com/EBIvariation/variation-commons/blob/develop/variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/repositories/VariantRepositoryImpl.java#L125) (right?), since VariantWithSamplesAndAnnotation is calling the method in VariantRepository (https://github.com/EBIvariation/variation-commons/blob/develop/variation-commons-mongodb/src/main/java/uk/ac/ebi/eva/commons/mongodb/services/VariantWithSamplesAndAnnotationsService.java#L186), it should be also excluding right? Or I am missing something? Thanks 😄

**Comment by cyenyxe** [comment]
The problem is that a previous version of the database schema stored all the information about the variants and their annotation in a single Mongo collection. We noticed that having these big documents was a performance bottleneck, and decided to extract the majority of the fields inside an annotation subdocument to another collection. We still keep the fields required for filtering in the variants collection.

As a result, now the repository is not the only place where we need to exclude the annotation from. The exclusion inside it only removes the annotation subdocument that remains in the variants collection, but not the information that `VariantWithSamplesAndAnnotationsService` brings from the annotation collection. 

You can use [this query](https://www.ebi.ac.uk/eva/webservices/rest/v1/segments/1:3000000-3100000/variants?species=ecaballus_20&page=1&skip=0&limit=10&exclude=annotation) to check that the annotation subdocument is present in the response.  The opposite case is the exclusion of "sourceEntries", which works via the repository because that information hasn't been extracted from the variants collection yet. You can test it using [this other query](https://www.ebi.ac.uk/eva/webservices/rest/v1/segments/1:3000000-3100000/variants?species=ecaballus_20&page=1&skip=0&limit=10&exclude=sourceEntries).

**Comment by tcezard** [comment]
Already track in a JIRA ticket: closing
