### ISSUE TITLE
EVA-981 Display main variant identifier

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-ws#88]
A [variant](https://github.com/EBIvariation/variation-commons/blob/develop/variation-commons-core/src/main/java/uk/ac/ebi/eva/commons/core/models/AbstractVariant.java) can have multiple identifiers:

 * SubSNP IDs, abbreviated as "ss"
 * RefSNP IDs, current and historical, abbreviated as "rs"

These are all stored in an attribute `ids`. The most recent rs ID is considered the main one. This fields was recently added as an attribute `id`, and we must ensure that it is part of the REST API response when searching for variants.

**Comment by AdrianBZG** [comment]
Hi @cyenyxe, just a question to make sure I'm understanding this clearly: the point is that the main identifier of a variant ([https://github.com/EBIvariation/variation-commons/blob/develop/variation-commons-core/src/main/java/uk/ac/ebi/eva/commons/core/models/AbstractVariant.java#L74](https://github.com/EBIvariation/variation-commons/blob/develop/variation-commons-core/src/main/java/uk/ac/ebi/eva/commons/core/models/AbstractVariant.java#L74)), should be returned together with the response in the /variants endpoint, that is what we want. Is this correct? Thanks.

**Comment by cyenyxe** [comment]
Yes, that's it. Maybe it will already be returned because it's in the model, but we need to make sure. It has to work for every endpoint that returns variants, which should be automatic once one of them works, but again we need to ensure that is the case :)

**Comment by tcezard** [comment]
Will continue to work on this in the Kira ticket: closing
